
# inherits = "dark_plus"
# inherits = "everforest_dark"
# inherits = "tokyonight"
# inherits = "bogster"
inherits = "gruvbox"

"ui.background"            = {bg = "#333333"}
"ui.cursor.primary.normal" = {fg = "#000000", bg = "#ffffff"}
"ui.cursor.primary.select" = {fg = "#000000", bg = "#8888ff"}
"ui.cursor.primary.insert" = {fg = "#000000", bg = "#88ff88"}

"ui.cursor.select"         = {fg = "#000000", bg = "#5555aa"}
"ui.cursor.insert"         = {fg = "#000000", bg = "#55aa55"}
"ui.cursor.normal"         = {fg = "#000000", bg = "#aaaaaa"}
"diagnostic.unnecessary"   = {fg = "#555555"}
