# dark_plus variant

inherits = "jk1"

# SYNTAX
"attribute"                 = "variable"
"comment"                   = "#00aa00"
"constant"                  = "variable"
"constant.builtin"          = "variable"
"constant.character"        = "variable"
"constant.character.escape" = "variable"
"constant.numeric"          = "#ffff00"
"constructor"               = "variable"
"diff.delta"                = "variable"
"diff.minus"                = "variable"
"diff.plus"                 = "variable"
"function"                  = "variable"
"function.builtin"          = "variable"
"function.macro"            = "variable"
"keyword"                   = "variable"
"keyword.control"           = "variable"
"keyword.directive"         = "variable"
"label"                     = "variable"
"module"                    = "variable"
"namespace"                 = "variable"
"operator"                  = "operator"
"punctuation"               = "operator"
"punctuation.delimiter"     = "operator"
"special"                   = "variable"
"string"                    = "variable"
"string.regexp"             = "variable"
"tag"                       = "variable"
"type"                      = "variable"
"type.builtin"              = "variable"
"type.enum.variant"         = "variable"
"variable"                  = "variable"
"variable.builtin"          = "variable"
"variable.other.member"     = "variable"
"variable.parameter"        = "variable"

# MARKUP
"markup.heading"       = { fg = "blue2", modifiers = ["bold"] }
"markup.list"          = "blue3"
"markup.bold"          = { modifiers = ["bold"] }
"markup.italic"        = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url"      = { underline.style= "line" }
"markup.link.text"     = "orange"
"markup.quote"         = "dark_green"
"markup.raw"           = "orange"

# UI
"ui.background"              = { fg = "light_gray", bg = "#000000" }
# "ui.background"              = { fg = "light_gray", bg = "dark_gray2" }
"ui.window"                  = { bg = "widget" }
"ui.popup"                   = { fg = "text", bg = "widget" }
"ui.help"                    = { fg = "text", bg = "widget" }
"ui.menu"                    = { fg = "text", bg = "widget" }
"ui.menu.selected"           = { bg = "dark_blue2" }
# TODO: Alternate bg colour for `ui.cursor.match` and `ui.selection`.
"ui.cursor"                  = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.primary"          = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.match"            = { bg = "#3a3d41", underline.style = "line" }
"ui.selection"               = { bg = "#3a3d41" }
"ui.selection.primary"       = { bg = "dark_blue" }
"ui.linenr"                  = { fg = "dark_gray" }
"ui.linenr.selected"         = { fg = "light_gray2" }
"ui.cursorline.primary"      = { bg = "dark_gray3" }
"ui.statusline"              = { fg = "white", bg = "#aa0000" }
"ui.statusline.inactive"     = { fg = "white", bg = "widget" }
"ui.statusline.insert"       = { fg = "white", bg = "yellow" }
"ui.statusline.select"       = { fg = "white", bg = "magenta" }
"ui.bufferline"              = { fg = "text", bg = "widget" }
"ui.bufferline.active"       = { fg = "black", bg = "#aa0000" }
"ui.bufferline.background"   = { bg = "background" }
"ui.text"                    = { fg = "text" }
"ui.text.focus"              = { fg = "white" }
"ui.text.directory"          = { fg = "blue2" }
"ui.text.inactive"           = { fg = "dark_gray" }
# "ui.virtual.whitespace"      = { fg = "dark_purple" }
"ui.virtual.whitespace"      = { fg = "#3e3e3d" }
"ui.virtual.wrap"            = { fg = "#3e3e3d" }
"ui.virtual.ruler"           = { bg = "borders" }
# "ui.virtual.indent-guide"    = { fg = "dark_purple" }
"ui.virtual.indent-guide"    = { fg = "dark_gray4" }
"ui.virtual.inlay-hint"      = { fg = "#aaaa00"}
"ui.virtual.jump-label"      = { fg = "yellow", modifiers = ["bold"] }
"ui.highlight.frameline"     = { bg = "#4b4b18" }
"ui.debug.active"            = { fg = "#ffcc00" }
"ui.debug.breakpoint"        = { fg = "#e51400" }
"ui.picker.header.column"    = { underline.style = "line" }
"ui.picker.header.column.active" = { fg ="white", underline.style = "line" }
"warning"                    = { fg = "gold2" }
"error"                      = { fg = "red" }
"info"                       = { fg = "grey" }
"hint"                       = { fg = "#aaaa00" }
"diagnostic.error".underline = { color = "red", style = "curl" }
"diagnostic".underline       = { color = "gold", style = "curl" }
"diagnostic.unnecessary"     = { modifiers = ["dim"] }
"diagnostic.deprecated"      = { modifiers = ["crossed_out"] }

[palette]
white = "#ffffff"
orange = "#ce9178"
gold = "#d7ba7d"
gold2 = "#cca700"
pale_green = "#b5cea8"
dark_green = "#6A9955"
dark_green2 = "#487e02"
light_gray = "#d4d4d4"
light_gray2 = "#c6c6c6"
light_gray3 = "#eeeeee"
dark_gray = "#858585"
dark_gray2 = "#1e1e1e"
dark_gray3 = "#282828"
dark_gray4 = "#404040"
dark_gray5 = "#8b949e"
blue = "#007acc"
blue2 = "#569CD6"
blue3 = "#6796E6"
blue4 = "#1b81a8"
light_blue = "#75beff"
dark_blue = "#264f78"
dark_blue2 = "#094771"
red = "#ff7777"
orange_red = "#f14c4c"
dark_purple = "#663388"

type = "#4EC9B0"
special = "#C586C0"
variable = "#ffffff"
fn_declaration = "#DCDCAA"
constant = "#4FC1FF"

background = "#1e1e1e"
text = "#d4d4d4"
cursor = "#a6a6a6"
widget = "#252526"
borders = "#323232"
operator = "#ff0000"



